### ISSUE TITLE
I'm interested in implementing support for Windows

### ISSUE THREAD

**Issue by JohnEricson** [Chassis/puppet-wp#140]
Hi @BronsonQuick!
It seems this module doesn't fully support Windows. I see installing the phar-file requires /usr/bin/curl among others on this line https://github.com/Chassis/puppet-wp/blob/master/manifests/cli.pp#L18 . I'm interested in implementing this in your module. If I send you a pull request would you be interested in merging it?

**Comment by BronsonQuick** [comment]
Hey @JohnEricson, ahh yes. We definitely hadn't considered Windows users looking at that. I'd definitely been keen for a PR from you for Windows support! Thanks

**Comment by JohnEricson** [comment]
Great! I'll let you know when I have it ready! 🙂

**Comment by BronsonQuick** [comment]
Fixed via: https://github.com/Chassis/puppet-wp/pull/141 💖
