### ISSUE TITLE
Version available on forge.puppetlabs.com should get a git tag

### ISSUE THREAD

**Issue by tremblaysimon** [Chassis/puppet-wp#31]
There is no tag so currently the master branch doesn't reflect what we get here https://forgeapi.puppetlabs.com/v3/files/rmccue-wp-1.0.1.tar.gz?_ga=1.45337380.1009363829.1434478680

**Comment by malaikah** [comment]
+1

**Comment by BronsonQuick** [comment]
Seeing this is now part of the Chassis organisation I've picked up maintainence and upgrades of this module. I've published a `1.1.1` release under a `chassis` username: https://forge.puppet.com/chassis/puppet_wp/

I'll be doing some more releases over the next few weeks and I'll add documentation on how to publish releases as well.
